logging:
  level:
    xyz:
      sunne:
        wls: debug

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/emphospatial?useUnicode=yes&characterEncoding=UTF8
    url: jdbc:mysql://www.sunne.xyz:3306/empt?useUnicode=yes&characterEncoding=UTF8
    password: xk8TP5iBEGDbMyNe
    username: wls_dev
    driver-class-name: com.mysql.jdbc.Driver
#    driver-class-name: com.mysql.cj.jdbc.Driver( mysql-connector-java 6)
    hikari:
      max-lifetime: 1765
      maximum-pool-size: 5
#custom:
#  rest:
#    connection:
#      connection-request-timeout: 3000
#      connect-timeout: 3000
#      connection.read-timeout: 3000
  http:
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 100Mb
#  redis:
#    host: localhost
#    port: 6379
##    password: 123456
#    timeout: 10000
#    pool:
#      max-active: 10
#      min-idle: 3
#      max-idle: 5
  aop:
    proxy-target-class: true
    auto: true
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  port: 1400
  connectionTimeout: 30000
  maxThreads: 400
  acceptCount: 500